name: VS Code Extension Publish

on:
  pull_request:
    types: [closed]
    branches: [develop, main]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "10.x"

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Determine target branch
        id: branch
        run: |
          echo "branch=${{ github.event.pull_request.base.ref }}" >> $GITHUB_OUTPUT

      - name: Pre-release publish on develop
        if: steps.branch.outputs.branch == 'develop'
        run: npm run publish:pre
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Full release publish on main
        if: steps.branch.outputs.branch == 'main'
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
